name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to install all dependencies legacy-peer-deps is used to avoid peer dependencies warnings
      - name: Install all dependencies
        run: npm install --legacy-peer-deps

      # Step to run tests
      # - name: Test
      # run: npm run test

      - name: Build for production
        run: npm run build

      # Step to create the build branch if it doesn't exist
      - name: Ensure build branch exists
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/build; then
            echo "Branch 'build' already exists."
            git checkout build
          else
            echo "Branch 'build' does not exist. Creating it."
            git checkout -b build
          fi
        shell: bash

      # Push build files to build branch
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message

      # Deploy to Hostinger via FTP
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTINGER_FTP_SERVER }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./dist/space-tourism-website-project/browser/
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
